### ISSUE TITLE
View All Books (back-end), User Story: 08P04 View all books

### ISSUE THREAD

**Issue by KarimElSheikh** [nelsammak/Croma#2]
User Story: View all books

**Comment by Veegas** [comment]
Gama3a please 7oto el routes beta3tko fe new file fe folder views badal ma heya fe app.js.
w law khalasto e3mlo pull request
@KarimElSheikh @MinaNemr

**Comment by Veegas** [comment]
w law khalasto e3mlo pull request

**Comment by Veegas** [comment]
momken kaman el frontend te7oto el controllers fe folder wel views fe folder mayb2oosh kolhom 3ala ba3d @MinaNemr

**Comment by Veegas** [comment]
@KarimElSheikh  fe app.js badal ma testakhdem mongoose.model('book')  3alatool e3ml fel awal var Books = require('./models/books')  w /models/book e3mel fel akher module.exports = mongoose.model('book', bookSchema)

**Comment by Veegas** [comment]
@KarimElSheikh Fih 7aga kaman maynfa3sh fe GET /books en enta teb3at html file mel folder beta3 el frontend, lazem teb3at JSON object beta3 el books bas w ba3deen @MinaNemr  yakhod el JSON w ye7otaha fel html be angular

**Comment by KarimElSheikh** [comment]
@Veegas done but I couldn't seperate the routes in a seperate file

**Comment by MinaNemr** [comment]
@Veegas  controllers seperated in seperate folder #1 
@Veegas  the front-end part arleady responds to JSON file

**Comment by KarimElSheikh** [comment]
@Veegas @nelsammak @omarkamal95 @Mernawaseif @Israa-Elwan @MinaNemr
Check my backend code in the branch "Library" and review it
