### ISSUE TITLE
View book bio (frontend)

### ISSUE THREAD

**Issue by MinaNemr** [nelsammak/Croma#5]

**Comment by omarkamal95** [comment]
@MinaNemr I reviewed the code, and i changed the logic behind linking the books.html. 1- Removed the ref to books.html from index.html. 2- Added the books route to app.js. 3- Added the books tab to the navbar dynamically from navbar.js to be only visible after authentication. 4- removed the script in books.html linking the controller and added it in index.html as everything is controlled from index.html using ng-view. 5- Removed the ng-app =" AppCtrl" from books.html as books is linked to the main app angularPassportApp which is linked in index.html. 6- Edited books.js module name to be angularPassportApp not AppCtrl.

**Comment by omarkamal95** [comment]
@MinaNemr Pictures not viewing on books page.

**Comment by omarkamal95** [comment]
Fixed book picture big.

**Comment by MinaNemr** [comment]
@omarkamal95 
okay Omar, I don't understand a lot of what you did :smile: but since the code is still working and you did a better structure that is great :+1:
